### ISSUE TITLE
code practice #1

### ISSUE THREAD

**Issue by saya1605** [KiranKhadd29/PracticeMAUI#2]
Jan 2023 Week 01:  target is to complete 5 videos in a week and deploy the code by weekend
#Vid_01
1. Setup MAUI Project
2. Setup Android/iOS emulator 
3. Create simple changes and debug

**Comment by KiranKhadd29** [comment]
- Navigation Page
- Flyout Page
- Tabbed Page
- Stack Page
- Grid Layout Page
